FROM debian:bullseye
RUN apt update && apt-get install -y --no-install-recommends sudo wget curl neofetch htop screenfetch python git python3-pip gnupg zsh tar locate firefox-esr net-tools liblttng-ust0 unzip make gpg gcc g++ terminator gobuster tty-clock nano vim nmap lynis aircrack-ng apktool gedit
RUN git clone https://github.com/Ashraf-wan/Corvid
WORKDIR "/Corvid"
RUN rm ~/.bashrc
RUN mv .bashrc ~
RUN mv logo /etc
RUN rm /etc/os-release
RUN mv os-release /etc
WORKDIR "/root"
RUN mkdir tools
WORKDIR "/root/tools"
RUN git clone https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
RUN git clone https://github.com/Z4nzu/hackingtool
RUN git clone https://github.com/trustedsec/social-engineer-toolkit/ setoolkit/ && pip3 install -r setoolkit/requirements.txt && python3 setoolkit/setup.py
RUN git clone https://github.com/vanhauser-thc/thc-hydra
RUN git clone https://github.com/sullo/nikto
RUN wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.5/powershell_7.1.5-1.debian.10_amd64.deb
RUN dpkg -i powershell_7.1.5-1.debian.10_amd64.deb
WORKDIR "/root/tools"
RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
RUN chmod 755 msfinstall
WORKDIR "/root/tools/thc-hydra"
RUN ./configure && make && make install
WORKDIR "/root/tools"
RUN GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest |  grep -oP '"tag_name": "\K(.*)(?=")') && wget https://github.com/zricethezav/gitleaks/releases/download/$GITLEAKS_VERSION/gitleaks-linux-amd64
RUN mv gitleaks-linux-amd64 gitleaks
RUN chmod +x gitleaks
RUN mv gitleaks /usr/local/bin/
RUN git clone https://github.com/RhinoSecurityLabs/pacu
RUN git clone https://github.com/RhinoSecurityLabs/CVEs
RUN git clone https://github.com/RhinoSecurityLabs/CloudScraper
RUN git clone https://github.com/RhinoSecurityLabs/dsnap
RUN git clone https://github.com/RhinoSecurityLabs/GCP-IAM-Privilege-Escalation
RUN git clone https://github.com/RhinoSecurityLabs/external_c2_framework
RUN git clone https://github.com/RhinoSecurityLabs/GCPBucketBrute
RUN git clone https://github.com/RhinoSecurityLabs/ccat 
RUN git clone https://github.com/RhinoSecurityLabs/Swagger-EZ
RUN git clone https://github.com/RhinoSecurityLabs/SleuthQL
WORKDIR "/root/tools"
# cleanup 
RUN apt-get clean
WORKDIR "/root/tools"
RUN rm powershell_7.1.5-1.debian.10_amd64.deb
WORKDIR "/root"
RUN useradd -m -p pakXq6/z0Zcdk corvid
RUN du -h --max-depth=1
