FROM debian:buster

ENV LANG=en_US.UTF-8
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      locales && \
    echo "$LANG UTF-8" >> /etc/locale.gen && \
    locale-gen && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      kwin-x11 \
      plasma-desktop \
      plasma-workspace && \
    apt-get remove -y bluedevil && \
    apt-get autoremove -y

# Dirty fix to avoid kdeinit error ind startkde. Did not find a proper solution.
RUN sed -i 's/.*kdeinit/###&/' /usr/bin/startkde

# Wayland: startplasmacompositor
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      kwin-wayland-backend-x11 kwin-wayland-backend-wayland && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      plasma-workspace-wayland && \
    sed -i 's/--libinput//' /usr/bin/startplasmacompositor
    
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      konsole \
      kwrite \
      libcups2 \
      libpulse0 \
      procps \
      psmisc \
      sudo \
      synaptic \
      systemsettings
RUN apt update && apt install --no-install-recommends sudo wget curl python git python3-pip firefox-esr net-tools unzip make gpg gobuster liblttng-ust0 nmap lynis aircrack-ng apktool -y
CMD startkde
WORKDIR "/root"
RUN mkdir tools
WORKDIR "/root/tools"
RUN git clone https://github.com/sqlmapproject/sqlmap.git sqlmap-dev
RUN git clone https://github.com/Z4nzu/hackingtool
RUN git clone https://github.com/trustedsec/social-engineer-toolkit/ setoolkit/
RUN git clone https://github.com/vanhauser-thc/thc-hydra
RUN git clone https://github.com/sullo/nikto
RUN wget https://github.com/PowerShell/PowerShell/releases/download/v7.1.5/powershell_7.1.5-1.debian.10_amd64.deb
RUN dpkg -i powershell_7.1.5-1.debian.10_amd64.deb
RUN echo 'deb http://download.opensuse.org/repositories/home:/cabelo/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/home:cabelo.list
RUN curl -fsSL https://download.opensuse.org/repositories/home:cabelo/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_cabelo.gpg > /dev/null
RUN apt update
RUN apt install owasp-zap
RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall
RUN chmod 755 msfinstall
RUN GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/zricethezav/gitleaks/releases/latest |  grep -oP '"tag_name": "\K(.*)(?=")') && wget https://github.com/zricethezav/gitleaks/releases/download/$GITLEAKS_VERSION/gitleaks-linux-amd64
RUN mv gitleaks-linux-amd64 gitleaks
RUN chmod +x gitleaks
RUN sudo mv gitleaks /usr/local/bin/
RUN git clone https://github.com/RhinoSecurityLabs/pacu
RUN git clone https://github.com/RhinoSecurityLabs/CVEs
RUN git clone https://github.com/RhinoSecurityLabs/CloudScraper
RUN git clone https://github.com/RhinoSecurityLabs/dsnap
RUN git clone https://github.com/RhinoSecurityLabs/GCP-IAM-Privilege-Escalation
RUN git clone https://github.com/RhinoSecurityLabs/external_c2_framework
RUN git clone https://github.com/RhinoSecurityLabs/GCPBucketBrute
RUN git clone https://github.com/RhinoSecurityLabs/ccat
RUN git clone https://github.com/RhinoSecurityLabs/Swagger-EZ
RUN git clone https://github.com/RhinoSecurityLabs/SleuthQL
RUN wget https://download.documentfoundation.org/libreoffice/stable/7.2.2/deb/x86_64/LibreOffice_7.2.2_Linux_x86-64_deb.tar.gz
RUN tar -xf LibreOffice_7.2.2_Linux_x86-64_deb.tar.gz
WORKDIR "LibreOffice_7.2.2.2_Linux_x86-64_deb/DEBS"
RUN dpkg -i *.deb
WORKDIR "/root/tools"
RUN rm LibreOffice_7.2.2_Linux_x86-64_deb.tar.gz
WORKDIR "/root"
CMD start
# cleanup & adding stuff
RUN apt-get clean
WORKDIR "/root/tools"
RUN rm powershell_7.1.5-1.debian.10_amd64.deb
RUN rm -r LibreOffice_7.2.2.2_Linux_x86-64_deb
WORKDIR "/root"
RUN useradd -m -p pakXq6/z0Zcdk corvid
RUN du -h --max-depth=1
